# Generated by Django 4.1.6 on 2023-02-05 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routine",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routineday",
            unique_together={("day", "routine")},
        ),
    ]
